name: Jekyll site CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod 777 /srv/jekyll && jekyll build --future"
        
    - name: Install coscmd
      run: sudo pip install coscmd
      
    - name: Configure coscmd
      env: 
        secret_id: ${{ secrets.SecretId }}
        secret_key: ${{ secrets.SecretKey }}
        bucket: ${{ secrets.BUCKET }}
        region: ap-guangzhou
      run: coscmd config -a $secret_id -s $secret_key -b $bucket -r $region
    - name: Upload to Tencent COS
      run: coscmd upload -rs --delete -f ./_site/ /